CREATE TABLE "LUNCHBOX"."JOURNAL" (
   ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
   MODIFICATIONDATE timestamp NOT NULL,
   PARAMS varchar(1024) NOT NULL,
   TEXTKEY varchar(255) NOT NULL,
   VERSION bigint,
   MODIFIER_ID bigint NOT NULL,
   CONSTRAINT primary_key PRIMARY KEY (ID)
);

ALTER TABLE "LUNCHBOX"."JOURNAL"
ADD CONSTRAINT JOURNALMODIFIER_ID
FOREIGN KEY (MODIFIER_ID)
REFERENCES "LUNCHBOX"."USERS"(ID);

CREATE INDEX SQL130517100923110 ON "LUNCHBOX"."JOURNAL"(MODIFIER_ID);
CREATE UNIQUE INDEX SQL130517100922880 ON "LUNCHBOX"."JOURNAL"(ID);

ALTER TABLE MEAL ALTER COLUMN HEADLINE NOT NULL;

ALTER TABLE OFFERITEM ALTER COLUMN MEAL_ID NOT NULL;
ALTER TABLE OFFERITEM ALTER COLUMN OFFER_ID NOT NULL;

DELETE FROM ORDERING WHERE ITEM_ID IS NULL;
ALTER TABLE ORDERING ALTER COLUMN ITEM_ID NOT NULL;
ALTER TABLE ORDERING ALTER COLUMN ORDERER_ID NOT NULL;

UPDATE OFFERITEM SET PRICEINCENTS=395 WHERE PRICEINCENTS=0
UPDATE OFFERITEM SET PRICEINCENTS=395 WHERE PRICEINCENTS=95

ALTER TABLE USERS ADD COLUMN LOGINNAME_ VARCHAR(50) DEFAULT '' NOT NULL;
UPDATE USERS SET LOGINNAME_=LOGINNAME;
ALTER TABLE USERS DROP COLUMN LOGINNAME;
RENAME COLUMN USERS.LOGINNAME_ TO LOGINNAME;

ALTER TABLE USERS ADD COLUMN LOGINSECRET_ VARCHAR(50) DEFAULT '' NOT NULL;
UPDATE USERS SET LOGINSECRET_=LOGINSECRET;
ALTER TABLE USERS DROP COLUMN LOGINSECRET;
RENAME COLUMN USERS.LOGINSECRET_ TO LOGINSECRET;

ALTER TABLE USERS ALTER COLUMN MAIL NOT NULL;

CREATE UNIQUE INDEX SQL130517100922881 ON "LUNCHBOX"."USERS"(LOGINNAME);

INSERT INTO DATABASECHANGELOG (ID,AUTHOR,FILENAME,DATEEXECUTED,ORDEREXECUTED,EXECTYPE,MD5SUM,DESCRIPTION,COMMENTS,TAG,LIQUIBASE) VALUES ('base','mayer','org/brainteam/lunchbox/db/changelog/db.changelog-0.0.1.xml',{ts '2013-05-17 10:09:23'},1,'EXECUTED','3:19c7d99adeae061d826844f9b784e363','Create Table (x6), Add Foreign Key Constraint (x5)','',null,'2.0.5');

